/** **listview config generate by KAKA LAZY TOOLS
*ENJOOY CODING!
*VERSION 0.1
*/
exports.title = '预购单管理'
exports.url = 'v2/admin/product/getpreorders'
exports.pageSize = 10
exports.items = {}
exports.items.no = {}
exports.items.no.index = 'no'
exports.items.no.label = '单号'
exports.items.no.filter = true
exports.items.productNo = {}
exports.items.productNo.index = 'productNo'
exports.items.productNo.label = '产品'
exports.items.count = {}
exports.items.count.index = 'count'
exports.items.count.label = '数量'
exports.items.voucherNo = {}
exports.items.voucherNo.index = 'voucherNo'
exports.items.voucherNo.label = '优惠券'
exports.items.userid = {}
exports.items.userid.index = 'userid'
exports.items.userid.label = '用户'
exports.items.userid.filter = true
// exports.items.userid.display='loginid';
// exports.items.userid.value='loginid';
// exports.items.userid.display='nickname';
// exports.items.userid.value='nickname';
exports.items.userid.display = 'name'
// exports.items.userid.value='name';
// exports.items.userid.display='idno';
// exports.items.userid.value='idno';
// exports.items.userid.display='mobile';
// exports.items.userid.value='mobile';
// exports.items.userid.display='status';
// exports.items.userid.value='status';
// exports.items.userid.display='lastlogin';
// exports.items.userid.value='lastlogin';
// exports.items.userid.display='with';
// exports.items.userid.value='with';
// exports.items.userid.display='withdate';
// exports.items.userid.value='withdate';
// exports.items.userid.display='headimgurl';
// exports.items.userid.value='headimgurl';
// exports.items.userid.display='dream1';
// exports.items.userid.value='dream1';
// exports.items.userid.display='dream2';
// exports.items.userid.value='dream2';
// exports.items.userid.display='checkidno';
// exports.items.userid.value='checkidno';
// exports.items.userid.display='invcode';
// exports.items.userid.value='invcode';
exports.items.status = {}
exports.items.status.index = 'status'
exports.items.status.label = 'status'
// exports.items.status.display='no';
// exports.items.status.value='no';
exports.items.status.display = 'name'
// exports.items.status.value='name';
exports.items.rechargeNo = {}
exports.items.rechargeNo.index = 'rechargeNo'
exports.items.rechargeNo.label = '充值单号'
exports.items.rechargeNo.display = 'no'
// exports.items.rechargeNo.value='no';
// exports.items.rechargeNo.display='amount';
// exports.items.rechargeNo.value='amount';
// exports.items.rechargeNo.display='sysamount';
// exports.items.rechargeNo.value='sysamount';
// exports.items.rechargeNo.display='useramount';
// exports.items.rechargeNo.value='useramount';
// exports.items.rechargeNo.display='status';
// exports.items.rechargeNo.value='status';
// exports.items.rechargeNo.display='userid';
// exports.items.rechargeNo.value='userid';
// exports.items.rechargeNo.display='chkuserid';
// exports.items.rechargeNo.value='chkuserid';
// exports.items.rechargeNo.display='bankid';
// exports.items.rechargeNo.value='bankid';
// exports.items.rechargeNo.display='time';
// exports.items.rechargeNo.value='time';
// exports.items.rechargeNo.display='desbankid';
// exports.items.rechargeNo.value='desbankid';
// exports.items.rechargeNo.display='chktime';
// exports.items.rechargeNo.value='chktime';
// exports.items.rechargeNo.display='success';
// exports.items.rechargeNo.value='success';
// exports.items.rechargeNo.display='type';
// exports.items.rechargeNo.value='type';
// exports.items.rechargeNo.display='body';
// exports.items.rechargeNo.value='body';
exports.items.buyNo = {}
exports.items.buyNo.index = 'buyNo'
exports.items.buyNo.label = '买单号'
// exports.items.buyNo.display='id';
// exports.items.buyNo.value='id';
exports.items.buyNo.display = 'no'
// exports.items.buyNo.value='no';
// exports.items.buyNo.display='count';
// exports.items.buyNo.value='count';
// exports.items.buyNo.display='limit';
// exports.items.buyNo.value='limit';
// exports.items.buyNo.display='feerate';
// exports.items.buyNo.value='feerate';
// exports.items.buyNo.display='ammount';
// exports.items.buyNo.value='ammount';
// exports.items.buyNo.display='userid';
// exports.items.buyNo.value='userid';
// exports.items.buyNo.display='usercointaccount';
// exports.items.buyNo.value='usercointaccount';
// exports.items.buyNo.display='transcount';
// exports.items.buyNo.value='transcount';
// exports.items.buyNo.display='transammount';
// exports.items.buyNo.value='transammount';
// exports.items.buyNo.display='status';
// exports.items.buyNo.value='status';
// exports.items.buyNo.display='lasttranstime';
// exports.items.buyNo.value='lasttranstime';
// exports.items.buyNo.display='region';
// exports.items.buyNo.value='region';
