exports.recharge = 'rechargelist'
exports.buylist = 'buylist'
exports.cashjourl = 'syscashjourallist'
exports.cashfee = 'cashfeelist'
exports.order = 'orderlist'
exports.sell = 'selllist'
exports.sysjounal = 'cashjourallist'
exports.withdral = 'withdrawlist'
exports.userlist = 'userlist'
exports.distributecoin = 'distributecoin'
exports.coinrecharge = 'coinrechargelist'
exports.selectitem = 'selectitem'
exports.userlist = 'userlist'
exports.ucjournal = 'usercoinjounallist'
exports.cashsettlement = 'cashsettmentlist'
exports.syscashsettlement = 'syscashsettmentlist'
exports.usercashsettlement = 'usercashsettmentlist'
exports.userjounal = 'userjounal'
exports.activitylist = 'activitylist'
exports.voucherlist = 'voucherlist'
exports.newscreate = 'newscreate'
exports.newslist = 'newslist'
exports.news = 'newsedit'
exports.authuser = 'authuser'
exports.useredit = 'useredit'
exports.newuser = 'newuser'
exports.activity = 'activity'
exports.syslog = 'syslog'
exports.loginlog = 'loginlog'
exports.changerechargeview = 'changerecharge'
exports.thirdpaychannel = 'paychannel'
exports.thirdpays = 'pays'
exports.thirdindoc = 'paymentindoc'
exports.cashsysaccounts = 'cash/cashaccountlist'
exports.cashcompanyaccounts = 'cash/sysaccountlist'
exports.invcodelist = 'activity/invcodelist'
exports.preoderlist = 'product/preoderlist'
exports.wechatuserlist = 'market/wechatuser'
exports.invrecord = 'activity/invrecord'

exports.dayreportuser = 'report/day/user'
exports.dayreportuserrb = 'report/day/userrb'
exports.listproduct = 'product/list'

exports.schlist = 'schedule/list'
exports.schitemlist = 'schedule/items'
exports.bonuslist = 'bonus/list'
exports.bonus = 'bonus/create'
exports.bonusitemlist = 'bonus/itemlist'

exports.dayreportrecharge = 'report/day/recharge'
exports.dayreportrechargeitem = 'report/day/rechargeitem'
exports.dayreporttrade = 'report/day/trade'
exports.dayreportwithrawal = 'report/day/withdrawal'
exports.dayreportusercoin = 'report/day/usercoin'

exports.regioncountris = 'region/list'
exports.payuserlist = 'payuser/list'
exports.createpayuser = 'payuser/create'

exports.authgrouplist = 'auth/userGroupList'
exports.createauthgroup = 'auth/createUserGroup'
exports.editUserGroup = 'auth/editUserGroup'
exports.editAuth = 'auth/editAuth'
exports.createauthgroupitem = 'auth/createAuthGroupItem'
exports.createauthitem = 'auth/createAuthItem'
exports.authlist = 'auth/authList'
exports.authlists = 'authlists'
exports.createauth = 'auth/createAuth'

exports.bankCardList = 'bankCardList'
exports.cashjournaldoclist = 'cash/cashJournalDocList'
exports.journaldoclist = 'cash/journalDocList'
exports.createjournaldoc = 'cash/createJournalDoc'
exports.createcashjournaldoc = 'cash/createCashJournalDoc'

exports.createuserfreezondoc = 'user/CreateFreezonDoc'
exports.createuserunfreezondoc = 'user/CreateUnFreezonDoc'
exports.userfreezondoclist = 'user/FreezonDocList'

exports.usercouponlist = 'activity/usercouponlist'
exports.invrecordlist = 'invatiation/recordlist'

exports.eventgrouplist = 'eventGroupList'
exports.editeventgroup = 'event/editEventGroup'
exports.createnotifygroup = 'event/createNotifyGroup'

exports.notifydefinelist = 'event/notifyDefineList'
exports.editnotifydefine = 'event/editNotifyDefine'
exports.createnotifydefine = 'event/createNotifyDefine'
exports.definelist = 'event/defineList'
exports.editdefine = 'event/editDefine'
exports.createdefine = 'event/createDefine'

exports.addtogroup = 'event/addToGroup'
